FROM    solr:6.6

COPY ./mysql-connector-java-5.1.46/mysql-connector-java-5.1.46.jar /opt/solr/dist/mysql-connector-java-5.1.46.jar
COPY ./mysql-connector-java-5.1.46/mysql-connector-java-5.1.46-bin.jar /opt/solr/dist/mysql-connector-java-5.1.46-bin.jar